### PR TITLE
fix: add ts-name config for package json name + rs-name for crate

### LINKED ISSUE #203: Readme should be updated with new options
After adding the output directory, we didnt update the readme.

### PR DESCRIPTION
**Pull request by shanejonas**
also fixes #203

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -14,6 +14,11 @@ program
     "JSON string or a Path/Url pointing to an open rpc schema",
     "./openrpc.json",
   )
+  .option(
```
Comment (BelfordZ) [inline src/cli.ts]: What about for rust client? 

IMO this should be a prefix, and the language should be arbitrarily appended to the prefix. For example:

prefix: foobar
generated name foobar-{language}

File: src/cli.ts [hunk 2]
```diff
@@ -14,6 +14,11 @@ program
...
+    "--ts-name [packageName]",
```
Comment (BelfordZ) [inline src/cli.ts]: should also add the rust one

File: src/index.ts [hunk 3]
```diff
@@ -34,6 +35,50 @@ const compileTemplate = async (
...
+const processRust = async (
+  destinationDirectoryName: string,
+  generatorOptions: IGeneratorOptions,
+) => {
+  const cargoTOMLPath = path.join(destinationDirectoryName, "Cargo.toml");
+  const fileContents = await readFile(cargoTOMLPath);
+  const cargoTOML = TOML.parse(fileContents.toString());
+  const updatedCargo = TOML.stringify({
+    ...cargoTOML,
+    package: {
```
Comment (mersinvald) [inline src/index.ts]: Looks like you’re rewriting the whole package section here, not just updating the name. That trims the edition flag, which would cause the failure we see on CI.

File: src/index.ts [hunk 4]
```diff
@@ -34,6 +35,51 @@ const compileTemplate = async (
...
+    name: generatorOptions.tsName,
+    version: generatorOptions.openrpcDocument.info.version,
+  });
+  await writeFile(packagePath, updatedPkg);
+};
+
+const postProcessStatic = async (
+  destinationDirectoryName: string,
+  generatorOptions: IGeneratorOptions,
+  language: string,
```
Comment (zcstarr) [inline src/index.ts]: nit. should this be TLanguage ?
