### PR TITLE
package.json doesnt include `templates`

### LINKED ISSUE #35: Error: Cannot find module '../templates/js/templated/exported-class.template.js'
**Describe the bug**
Error: Cannot find module '../templates/js/templated/exported-class.template.js'

**To Reproduce**
1. `npm install -g @open-rpc/generator-client`
2. `open-rpc-generator-client -s https://raw.githubusercontent.com/etclabscore/multi-geth/0718d25e92e568f486be17123e9384ce15d8b48c/openrpc.json EthClient`
3. See error screenshot

**Expected behavior**
Should build a client no errors
 
**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 1.0.25

### PR DESCRIPTION
**Pull request by shanejonas**
fixes #35 

this renames package.json to `_package.json` to get around `npm publish` not including directories with `package.json` files. cant get around it by using `files: []`

**TODO**: 
- [ ] deploy version 1.0.28 via `npm publish`

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -71,7 +71,8 @@ const copyStatic = async (destinationDirectoryName) => {
   await fsx.emptyDir(destinationDirectoryName);
 
   const staticPath = path.join(__dirname, '../', '/templates/js/static');
-  fsx.copy(staticPath, destinationDirectoryName);
+  await fsx.copy(staticPath, destinationDirectoryName);
+  await fsx.move(path.join(destinationDirectoryName, '_package.json'), path.join(destinationDirectoryName, 'package.json'));
```
Comment (BelfordZ) [inline src/index.js]: can u make this as another PR? 

not a fan.

**Comment by shanejonas** [comment]
it feels gross. but npm has forced this upon us
